### ISSUE TITLE
Internal Server Error - Empty Fill-in Fields (Event Start/Event End)

### ISSUE THREAD

**Issue by C-Carter10** [josev814/csc470_ntss#47]
Returns an Internal Server Error when trying to save new event without adding the start date/time and end date/time as NTSS ADMIN (potentially as Event Staff too)
- Check All Fields (after fixed)
![image](https://github.com/josev814/csc470_ntss/assets/145708835/ffee9ba9-8b5d-494c-8969-4acc0620dfd7)
![image](https://github.com/josev814/csc470_ntss/assets/145708835/affcacf2-8472-422b-b446-3ce10cc207dc)
![image](https://github.com/josev814/csc470_ntss/assets/145708835/fa62d658-75ac-44e7-a3bc-36e1df5c324d)

**Comment by josev814** [comment]
@C-Carter10 the event start and end dates should always be required.  So we should make the html element state that it's required.

**Comment by josev814** [comment]
@C-Carter10 A fix for this was merged into main for the NTSS Admin when doing Add Event.  Feel free to check this out, and the resolve this issue if it's fixed.
